language: minimal

script:
  - chmod u+rwx ./test/build_and_run_tests.sh
  - ./test/build_and_run_tests.sh no_ssl nginx nginx_no_x_forward nginx_444 ei redis_1 redis_120

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  - provider: script
    script: docker tag localhost:5000/linksmart/bgw:test linksmart/bgw:latest && docker push linksmart/bgw:latest
    on:
      branch: master
  - provider: script
    script: docker tag localhost:5000/linksmart/bgw:test linksmart/bgw:snapshot && docker push linksmart/bgw:snapshot
    on:
      branch: dev
  - provider: script
    script: docker tag localhost:5000/linksmart/bgw:test linksmart/bgw:${TRAVIS_TAG} &&
      docker push linksmart/bgw:${TRAVIS_TAG}
    on:
      tags: true
