FROM debian:jessie-slim

RUN apt-get update && apt-get install -y curl jq

RUN apt-get install -y apt-transport-https ca-certificates gnupg2 software-properties-common

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install -y nodejs

RUN curl -fsSL http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key | apt-key add -
RUN add-apt-repository "deb https://repo.mosquitto.org/debian jessie main"
RUN apt-get update
RUN apt-get install -y mosquitto-clients

RUN npm install -g newman

COPY ./test/generic_websocket /bgw/test/generic_websocket
WORKDIR /bgw/test/generic_websocket
RUN npm install

COPY ./test/mqtt_over_websocket /bgw/test/mqtt_over_websocket
WORKDIR /bgw/test/mqtt_over_websocket
RUN npm install

COPY ./logger /bgw/logger
WORKDIR /bgw/logger
RUN npm install

COPY ./certs /bgw/certs

COPY ./test/test.sh /bgw/test
COPY ./test/test_ws_and_mqtt.sh /bgw/test
COPY ./test/test_border_gateway.postman_collection.json /bgw/test
WORKDIR /bgw/test

RUN chmod -R +x *.sh



