FROM node:12-alpine

RUN apk update && apk upgrade && apk --no-cache add bash && apk --no-cache add jq && apk --no-cache add expect && apk --no-cache add mosquitto-clients && apk --no-cache add curl && apk --no-cache add procps

RUN npm install -g newman

COPY ./test/generic_websocket /bgw/test/generic_websocket
WORKDIR /bgw/test/generic_websocket
RUN npm install

COPY ./test/mqtt_over_websocket /bgw/test/mqtt_over_websocket
WORKDIR /bgw/test/mqtt_over_websocket
RUN npm install

COPY ./logger /bgw/logger
WORKDIR /bgw/logger
RUN npm install

COPY ./certs /bgw/certs

COPY ./test/test.sh /bgw/test
COPY ./test/test_ws_and_mqtt.sh /bgw/test
COPY ./test/test_border_gateway.postman_collection.json /bgw/test
WORKDIR /bgw/test

RUN chmod -R +x *.sh

ENTRYPOINT ["./test.sh"]


