FROM node:12-alpine

RUN apk update && apk upgrade && apk add bash && apk add jq && apk add expect && apk add mosquitto-clients && apk add curl

RUN npm install -g newman

COPY ./test/generic_websocket /bgw/test/generic_websocket
WORKDIR /bgw/test/generic_websocket
RUN npm install

COPY ./test/mqtt_over_websocket /bgw/test/mqtt_over_websocket
WORKDIR /bgw/test/mqtt_over_websocket
RUN npm install

COPY ./logger /bgw/logger
WORKDIR /bgw/logger
RUN npm install

COPY ./certs /bgw/certs

COPY ./test/test.sh /bgw/test
COPY ./test/test_ws_and_mqtt.sh /bgw/test
COPY ./test/test_border_gateway.postman_collection.json /bgw/test
WORKDIR /bgw/test

RUN chmod -R +x *.sh

ENTRYPOINT ["./test.sh"]


